# Generated by Django 3.2.13 on 2022-04-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturi',
            name='description',
            field=models.CharField(help_text='Helps you remember what this URI is about', max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='shorturi',
            name='full_uri',
            field=models.URLField(help_text='The actual URI', max_length=255, verbose_name='Full URI'),
        ),
    ]
